# Generated by Django 3.2 on 2022-02-11 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_auto_20220211_2244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carbrand',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='carbrand',
            old_name='updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='carmodel',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='carmodel',
            old_name='updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='usercar',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='usercar',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
