# Generated by Django 3.2 on 2022-02-13 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_auto_20220213_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='car_brand',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='car_brand', to='car.carbrand'),
        ),
    ]
